# Generated by Django 3.2.16 on 2022-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20221214_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
