# Generated by Django 3.2.16 on 2022-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_course_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='current',
            field=models.IntegerField(),
        ),
    ]
