# Generated by Django 3.2.16 on 2022-12-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_course_current'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Quotation',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='course',
            new_name='quotation',
        ),
    ]
