# Generated by Django 3.2.16 on 2022-12-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20221214_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.quotation'),
        ),
    ]
