# Generated by Django 3.2.16 on 2022-12-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_product_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quotation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.quotation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
